// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSVkCLffuipx48V44tXuml45wd3g3C5Ig',
    appId: '1:30593220241:web:6be33ecd64d85d36c24930',
    messagingSenderId: '30593220241',
    projectId: 'pills-49c63',
    authDomain: 'pills-49c63.firebaseapp.com',
    storageBucket: 'pills-49c63.appspot.com',
    measurementId: 'G-MF7XGD4QCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJe0mI6jW1GGZv79hw67uRRtixNABlusU',
    appId: '1:30593220241:android:c87af72af7dcd98cc24930',
    messagingSenderId: '30593220241',
    projectId: 'pills-49c63',
    storageBucket: 'pills-49c63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzbj5p3nBK_UOeiAfneOYpI-YrQ-Fkq1o',
    appId: '1:30593220241:ios:7944207b13c9a9c1c24930',
    messagingSenderId: '30593220241',
    projectId: 'pills-49c63',
    storageBucket: 'pills-49c63.appspot.com',
    iosClientId: '30593220241-8jps8hcujfgruviu8hu8h8ageken6fv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pillsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzbj5p3nBK_UOeiAfneOYpI-YrQ-Fkq1o',
    appId: '1:30593220241:ios:7944207b13c9a9c1c24930',
    messagingSenderId: '30593220241',
    projectId: 'pills-49c63',
    storageBucket: 'pills-49c63.appspot.com',
    iosClientId: '30593220241-8jps8hcujfgruviu8hu8h8ageken6fv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pillsApp',
  );
}
